# Generated by Django 5.1.4 on 2025-04-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_avatar_userprofile_karma'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='charges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='lawyers',
            field=models.ManyToManyField(blank=True, to='core.lawyer'),
        ),
    ]
