# Generated by Django 5.1.4 on 2025-04-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_case_charges_case_lawyers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='charges',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
