# Generated by Django 5.1.4 on 2025-04-13 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_case_charges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_upvotes', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('voter', 'voted')},
            },
        ),
    ]
